// vue/src/components/Button/Button.vue
<script setup lang="ts">
import { computed, useSlots } from 'vue'

export type ButtonVariant = 'primary' | 'secondary'
export type ButtonAppearance = 'solid' | 'outline' | 'ghost'
export type ButtonSize = 'xs' | 'sm' | 'md' | 'lg'

interface Props {
  /** Jerarquía visual del botón. */
  variant?: ButtonVariant
  /** Estilo de superficie: relleno, borde o transparente. */
  appearance?: ButtonAppearance
  /** Tamaño del botón. */
  size?: ButtonSize
  /** Desactiva el botón. */
  disabled?: boolean
  /** Muestra un spinner y bloquea el botón. */
  loading?: boolean
  /** Tipo del <button>. Default: 'button'. */
  type?: 'button' | 'submit' | 'reset'
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'primary',
  appearance: 'solid',
  size: 'md',
  disabled: false,
  loading: false,
  type: 'button',
})

defineEmits<{
  (e: 'click', event: MouseEvent): void
}>()

const slots = useSlots()

const classes = computed(() => [
  'and-btn',
  `and-btn--${props.appearance}-${props.variant}`,
  `and-btn--size-${props.size}`,
  props.loading && 'and-btn--loading',
])

const isDisabled = computed(() => props.disabled || props.loading)
</script>

<template>
  <button
    :type="type"
    :class="classes"
    :disabled="isDisabled"
    :aria-busy="loading || undefined"
    @click="$emit('click', $event)"
  >
    <span v-if="loading" class="and-btn__spinner" aria-hidden="true" />
    <span
      v-else-if="slots.leftIcon"
      class="and-btn__icon and-btn__icon--left"
      aria-hidden="true"
    >
      <slot name="leftIcon" />
    </span>

    <span v-if="slots.default" class="and-btn__label">
      <slot />
    </span>

    <span
      v-if="slots.rightIcon && !loading"
      class="and-btn__icon and-btn__icon--right"
      aria-hidden="true"
    >
      <slot name="rightIcon" />
    </span>
  </button>
</template>

<style src="./Button.css"></style>

// react/src/components/Button/Button.tsx
import * as React from 'react'
import './Button.css'

export type ButtonVariant = 'primary' | 'secondary'
export type ButtonAppearance = 'solid' | 'outline' | 'ghost'
export type ButtonSize = 'xs' | 'sm' | 'md' | 'lg'

export interface ButtonProps
  extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, 'children'> {
  /** Jerarquía visual del botón. */
  variant?: ButtonVariant
  /** Estilo de superficie: relleno, borde o transparente. */
  appearance?: ButtonAppearance
  /** Tamaño del botón. */
  size?: ButtonSize
  /** Muestra un spinner y bloquea el botón. */
  loading?: boolean
  /** Icono a la izquierda del label. */
  leftIcon?: React.ReactNode
  /** Icono a la derecha del label. */
  rightIcon?: React.ReactNode
  /** Contenido del botón (label). */
  children?: React.ReactNode
}

/**
 * Button — componente unificado del DS Andromeda.
 *
 * Reemplaza los ~20 component sets fragmentados de Figma
 * (`btn/primary-SM`, `btn/ghost-primary-MD`, etc.) por una única
 * API con properties `variant`, `appearance` y `size`.
 */
export const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  function Button(
    {
      variant = 'primary',
      appearance = 'solid',
      size = 'md',
      loading = false,
      disabled,
      leftIcon,
      rightIcon,
      children,
      className,
      type = 'button',
      ...rest
    },
    ref,
  ) {
    const classes = [
      'and-btn',
      `and-btn--${appearance}-${variant}`,
      `and-btn--size-${size}`,
      loading && 'and-btn--loading',
      className,
    ]
      .filter(Boolean)
      .join(' ')

    const isDisabled = disabled || loading

    return (
      <button
        ref={ref}
        type={type}
        className={classes}
        disabled={isDisabled}
        aria-busy={loading || undefined}
        {...rest}
      >
        {loading ? (
          <span className="and-btn__spinner" aria-hidden="true" />
        ) : (
          leftIcon && (
            <span className="and-btn__icon and-btn__icon--left" aria-hidden="true">
              {leftIcon}
            </span>
          )
        )}
        {children && <span className="and-btn__label">{children}</span>}
        {rightIcon && !loading && (
          <span className="and-btn__icon and-btn__icon--right" aria-hidden="true">
            {rightIcon}
          </span>
        )}
      </button>
    )
  },
)

Button.displayName = 'Button'
