// react/src/components/Table/Table.tsx
import { useMemo, useState, type HTMLAttributes, type ReactNode } from 'react'
import { Checkbox } from '../Controls'
import { Icon } from '../Icon'
import './Table.css'

export type TableAlign = 'left' | 'center' | 'right'
export type TableSortDirection = 'asc' | 'desc'

export interface TableColumn<Row = Record<string, unknown>> {
  /** Clave del dato en la fila */
  key: string
  /** Título del header (Figma: "Texto Titulo"; vacío = "Mostrar Texto" off) */
  title?: string
  /** Alineación (Figma: Estados Izq/Centrado/Der del Item Columna) */
  align?: TableAlign
  /** Header ordenable asc/desc (Figma: icono unfold) */
  sortable?: boolean
  width?: number | string
  /** Render de la celda: integra cualquier componente de la librería */
  render?: (row: Row, rowIndex: number) => ReactNode
}

export interface TableProps<Row = Record<string, unknown>>
  extends Omit<HTMLAttributes<HTMLTableElement>, 'children'> {
  columns: TableColumn<Row>[]
  data: Row[]
  /** Filas alternas con fondo background (estado Select de Figma) */
  zebra?: boolean
  /** Columna de selección con el Checkbox de la librería */
  selectable?: boolean
  /** Índices seleccionados (controlado) */
  selected?: number[]
  onSelectionChange?: (selected: number[]) => void
  /** Orden activo (no controlado internamente si se pasa) */
  onSortChange?: (key: string | null, direction: TableSortDirection | null) => void
}

export function Table<Row extends Record<string, unknown>>({
  columns,
  data,
  zebra = true,
  selectable = false,
  selected,
  onSelectionChange,
  onSortChange,
  className = '',
  ...rest
}: TableProps<Row>) {
  const [sort, setSort] = useState<{
    key: string
    direction: TableSortDirection
  } | null>(null)
  const [innerSelected, setInnerSelected] = useState<number[]>([])
  const currentSelected = selected !== undefined ? selected : innerSelected

  // Click en el título: asc -> desc -> sin orden
  const toggleSort = (key: string) => {
    let next: { key: string; direction: TableSortDirection } | null
    if (sort?.key !== key) next = { key, direction: 'asc' }
    else if (sort.direction === 'asc') next = { key, direction: 'desc' }
    else next = null
    setSort(next)
    onSortChange?.(next?.key ?? null, next?.direction ?? null)
  }

  const sortedIndexes = useMemo(() => {
    const indexes = data.map((_, i) => i)
    if (!sort) return indexes
    const { key, direction } = sort
    return indexes.sort((a, b) => {
      const va = data[a][key]
      const vb = data[b][key]
      let cmp: number
      if (typeof va === 'number' && typeof vb === 'number') cmp = va - vb
      else cmp = String(va ?? '').localeCompare(String(vb ?? ''), 'es', { numeric: true })
      return direction === 'asc' ? cmp : -cmp
    })
  }, [data, sort])

  const commitSelection = (next: number[]) => {
    if (selected === undefined) setInnerSelected(next)
    onSelectionChange?.(next)
  }

  const allSelected = data.length > 0 && currentSelected.length === data.length

  const alignThClass = (align?: TableAlign) =>
    align === 'left'
      ? ' and-table__th--left'
      : align === 'right'
        ? ' and-table__th--right'
        : ''

  const alignTdClass = (align?: TableAlign) =>
    align === 'center'
      ? ' and-table__td--center'
      : align === 'right'
        ? ' and-table__td--right'
        : ''

  return (
    <div className="and-table-wrap">
      <table
        className={['and-table', zebra && 'and-table--zebra', className]
          .filter(Boolean)
          .join(' ')}
        {...rest}
      >
        <thead>
          <tr>
            {selectable && (
              <th className="and-table__th and-table__check-cell">
                <Checkbox
                  checked={allSelected}
                  onChange={(checked) =>
                    commitSelection(checked ? data.map((_, i) => i) : [])
                  }
                />
              </th>
            )}
            {columns.map((col) => (
              <th
                key={col.key}
                className={`and-table__th${alignThClass(col.align)}`}
                style={col.width !== undefined ? { width: col.width } : undefined}
                aria-sort={
                  sort?.key === col.key
                    ? sort.direction === 'asc'
                      ? 'ascending'
                      : 'descending'
                    : undefined
                }
              >
                <span className="and-table__th-inner">
                  {col.title}
                  {col.sortable && (
                    <button
                      type="button"
                      className="and-table__sort"
                      aria-label={`Ordenar por ${col.title ?? col.key}`}
                      onClick={() => toggleSort(col.key)}
                    >
                      <Icon
                        name={
                          sort?.key === col.key
                            ? sort.direction === 'asc'
                              ? 'chevron-up'
                              : 'chevron-down'
                            : 'unfold'
                        }
                        size={24}
                      />
                    </button>
                  )}
                </span>
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {sortedIndexes.map((rowIndex) => {
            const row = data[rowIndex]
            const isSelected = currentSelected.includes(rowIndex)
            return (
              <tr
                key={rowIndex}
                className={isSelected && !zebra ? 'and-table__tr--select' : undefined}
              >
                {selectable && (
                  <td className="and-table__td and-table__check-cell">
                    <Checkbox
                      checked={isSelected}
                      onChange={(checked) =>
                        commitSelection(
                          checked
                            ? [...currentSelected, rowIndex]
                            : currentSelected.filter((i) => i !== rowIndex),
                        )
                      }
                    />
                  </td>
                )}
                {columns.map((col) => (
                  <td
                    key={col.key}
                    className={`and-table__td${alignTdClass(col.align)}`}
                  >
                    {col.render
                      ? col.render(row, rowIndex)
                      : (row[col.key] as ReactNode)}
                  </td>
                ))}
              </tr>
            )
          })}
        </tbody>
      </table>
    </div>
  )
}

// vue/src/components/Table/Table.vue
<script setup lang="ts" generic="Row extends Record<string, unknown>">
import { computed, ref } from 'vue'
import Checkbox from '../Controls/Checkbox.vue'
import Icon from '../Icon/Icon.vue'
import './Table.css'

/*
 * Table — DS Andromeda (Figma: sets "Título Columna" 14121:1560,
 * "Item Columna" 138:1658 y "Table items" 13661:10043, página Tables
 * 9811:37509). Header de 55px con títulos 12 Medium secondary-light
 * en mayúsculas y orden asc/desc (icono unfold en primary → chevron
 * up/down); celdas de 50px con 14px body y alineación Izq/Centrado/
 * Der; filas alternas con el estado Select (fondo background) y
 * columna opcional de Checkbox de la librería. Las celdas aceptan
 * cualquier componente vía el slot `cell`. Responsivo: en <768px
 * adopta las alturas del diseño Movil (40/36) con scroll horizontal.
 */

export type TableAlign = 'left' | 'center' | 'right'
export type TableSortDirection = 'asc' | 'desc'

export interface TableColumn {
  key: string
  title?: string
  align?: TableAlign
  sortable?: boolean
  width?: number | string
}

interface TableProps {
  columns: TableColumn[]
  data: Row[]
  /** Filas alternas con fondo background (estado Select de Figma). */
  zebra?: boolean
  /** Columna de selección con el Checkbox de la librería. */
  selectable?: boolean
}

const props = withDefaults(defineProps<TableProps>(), {
  zebra: true,
  selectable: false,
})

const emit = defineEmits<{
  selectionChange: [selected: number[]]
  sortChange: [key: string | null, direction: TableSortDirection | null]
}>()

const sort = ref<{ key: string; direction: TableSortDirection } | null>(null)
const selected = ref<number[]>([])

// Click en el título: asc -> desc -> sin orden
const toggleSort = (key: string) => {
  if (sort.value?.key !== key) sort.value = { key, direction: 'asc' }
  else if (sort.value.direction === 'asc') sort.value = { key, direction: 'desc' }
  else sort.value = null
  emit('sortChange', sort.value?.key ?? null, sort.value?.direction ?? null)
}

const sortedIndexes = computed(() => {
  const indexes = props.data.map((_, i) => i)
  if (!sort.value) return indexes
  const { key, direction } = sort.value
  return [...indexes].sort((a, b) => {
    const va = props.data[a][key]
    const vb = props.data[b][key]
    let cmp: number
    if (typeof va === 'number' && typeof vb === 'number') cmp = va - vb
    else cmp = String(va ?? '').localeCompare(String(vb ?? ''), 'es', { numeric: true })
    return direction === 'asc' ? cmp : -cmp
  })
})

const allSelected = computed(
  () => props.data.length > 0 && selected.value.length === props.data.length,
)

const toggleAll = (checked: boolean) => {
  selected.value = checked ? props.data.map((_, i) => i) : []
  emit('selectionChange', selected.value)
}

const toggleRow = (rowIndex: number, checked: boolean) => {
  selected.value = checked
    ? [...selected.value, rowIndex]
    : selected.value.filter((i) => i !== rowIndex)
  emit('selectionChange', selected.value)
}

const thClass = (align?: TableAlign) => [
  'and-table__th',
  align === 'left' && 'and-table__th--left',
  align === 'right' && 'and-table__th--right',
]

const tdClass = (align?: TableAlign) => [
  'and-table__td',
  align === 'center' && 'and-table__td--center',
  align === 'right' && 'and-table__td--right',
]
</script>

<template>
  <div class="and-table-wrap">
    <table :class="['and-table', zebra && 'and-table--zebra']">
      <thead>
        <tr>
          <th v-if="selectable" class="and-table__th and-table__check-cell">
            <Checkbox :model-value="allSelected" @change="toggleAll" />
          </th>
          <th
            v-for="col in columns"
            :key="col.key"
            :class="thClass(col.align)"
            :style="col.width !== undefined ? { width: typeof col.width === 'number' ? `${col.width}px` : col.width } : undefined"
            :aria-sort="
              sort?.key === col.key
                ? sort.direction === 'asc'
                  ? 'ascending'
                  : 'descending'
                : undefined
            "
          >
            <span class="and-table__th-inner">
              {{ col.title }}
              <button
                v-if="col.sortable"
                type="button"
                class="and-table__sort"
                :aria-label="`Ordenar por ${col.title ?? col.key}`"
                @click="toggleSort(col.key)"
              >
                <Icon
                  :name="
                    sort?.key === col.key
                      ? sort.direction === 'asc'
                        ? 'chevron-up'
                        : 'chevron-down'
                      : 'unfold'
                  "
                  :size="24"
                />
              </button>
            </span>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="rowIndex in sortedIndexes" :key="rowIndex">
          <td v-if="selectable" class="and-table__td and-table__check-cell">
            <Checkbox
              :model-value="selected.includes(rowIndex)"
              @change="(checked) => toggleRow(rowIndex, checked)"
            />
          </td>
          <td v-for="col in columns" :key="col.key" :class="tdClass(col.align)">
            <slot
              name="cell"
              :row="data[rowIndex]"
              :column="col"
              :row-index="rowIndex"
            >
              {{ data[rowIndex][col.key] }}
            </slot>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
