// react/src/components/Tabs/Tabs.tsx
import { useState, type HTMLAttributes, type ReactNode } from 'react'
import { Icon, type AndIconName } from '../Icon'
import './Tabs.css'

export interface TabItem {
  /** Texto del tab (Figma: "Texto" / "Text content") */
  label: string
  /** Icono izquierdo de la librería (Figma: "Cambiar Icono Izq"; omitir = "Mostrar Icono Izq" off) */
  iconLeft?: AndIconName
  /** Icono derecho de la librería (Figma: "Cambiar Icono Der") */
  iconRight?: AndIconName
  /** Estado Disabled (solo variante primary) */
  disabled?: boolean
}

export interface TabsProps
  extends Omit<HTMLAttributes<HTMLDivElement>, 'onChange'> {
  /** Tabs (strings u objetos con iconos/disabled) */
  items: Array<string | TabItem>
  /** Índice activo (controlado) */
  active?: number
  defaultActive?: number
  onChange?: (index: number, item: TabItem) => void
  /** primary: Tabs-1 con subrayado · secondary: Tab secundario (segmented) */
  variant?: 'primary' | 'secondary'
  /** Color del subrayado activo del primary (Figma: Active primary/Active secundary) */
  activeStyle?: 'primary' | 'secondary'
  /** Icono de la librería aplicado a todos los tabs del primary */
  icon?: AndIconName
  /** Lado donde va el icono: izquierdo, derecho o ambos */
  iconPosition?: 'left' | 'right' | 'both'
}

const toItems = (items: Array<string | TabItem>): TabItem[] =>
  items.map((i) => (typeof i === 'string' ? { label: i } : i))

export function Tabs({
  items,
  active,
  defaultActive = 0,
  onChange,
  variant = 'primary',
  activeStyle = 'primary',
  icon,
  iconPosition = 'both',
  className = '',
  ...rest
}: TabsProps) {
  const [inner, setInner] = useState(defaultActive)
  const current = active !== undefined ? active : inner
  const tabs = toItems(items)

  const select = (index: number) => {
    if (tabs[index].disabled) return
    if (active === undefined) setInner(index)
    onChange?.(index, tabs[index])
  }

  if (variant === 'secondary') {
    return (
      <div
        className={['and-tabs--segmented', className].filter(Boolean).join(' ')}
        role="tablist"
        {...rest}
      >
        {tabs.map((tab, i) => (
          <button
            key={i}
            type="button"
            role="tab"
            aria-selected={i === current}
            className={[
              'and-tabs__segment',
              i === current && 'and-tabs__segment--active',
            ]
              .filter(Boolean)
              .join(' ')}
            onClick={() => select(i)}
          >
            {tab.label}
          </button>
        ))}
      </div>
    )
  }

  const renderIcon = (name?: AndIconName): ReactNode =>
    name ? <Icon name={name} size={24} /> : null

  // `icon` + `iconPosition` aplican a todos los tabs; el item puede
  // sobreescribir con sus propios iconLeft/iconRight
  const leftIconOf = (tab: TabItem) =>
    tab.iconLeft ??
    (icon && (iconPosition === 'left' || iconPosition === 'both') ? icon : undefined)

  const rightIconOf = (tab: TabItem) =>
    tab.iconRight ??
    (icon && (iconPosition === 'right' || iconPosition === 'both') ? icon : undefined)

  return (
    <div
      className={[
        'and-tabs',
        activeStyle === 'secondary' && 'and-tabs--secondary-style',
        className,
      ]
        .filter(Boolean)
        .join(' ')}
      role="tablist"
      {...rest}
    >
      {tabs.map((tab, i) => (
        <button
          key={i}
          type="button"
          role="tab"
          aria-selected={i === current}
          disabled={tab.disabled}
          className={[
            'and-tabs__tab',
            i === current && !tab.disabled && 'and-tabs__tab--active',
          ]
            .filter(Boolean)
            .join(' ')}
          onClick={() => select(i)}
        >
          <span className="and-tabs__tab-inner">
            {renderIcon(leftIconOf(tab))}
            {tab.label}
            {renderIcon(rightIconOf(tab))}
          </span>
          <span className="and-tabs__bar" aria-hidden="true" />
        </button>
      ))}
    </div>
  )
}

// vue/src/components/Tabs/Tabs.vue
<script setup lang="ts">
import { computed } from 'vue'
import Icon from '../Icon/Icon.vue'
import type { AndIconName } from '../Icon/icons'
import './Tabs.css'

/*
 * Tabs — DS Andromeda (Figma: sets "Tabs-1" 175:4777 — tab primary
 * con subrayado de 4px (Default/Disabled/Active primary/Active
 * secundary) —, "Tab secundario" 14033:4376 — segmented control con
 * fondo gray-200 — y "Tab-atom" 14031:9608). Un solo componente
 * responsivo: en <768px el primary usa texto de 14px con iconos de
 * 20px y el segmented pierde el ancho mínimo y hace scroll.
 * v-model con el índice activo.
 */

export interface TabItem {
  /** Texto del tab (Figma: "Texto" / "Text content"). */
  label: string
  /** Icono izquierdo de la librería (Figma: "Cambiar Icono Izq"). */
  iconLeft?: AndIconName
  /** Icono derecho de la librería (Figma: "Cambiar Icono Der"). */
  iconRight?: AndIconName
  /** Estado Disabled (solo variante primary). */
  disabled?: boolean
}

interface TabsProps {
  /** Tabs (strings u objetos con iconos/disabled). */
  items: Array<string | TabItem>
  /** primary: Tabs-1 con subrayado · secondary: Tab secundario (segmented). */
  variant?: 'primary' | 'secondary'
  /** Color del subrayado activo (Figma: Active primary/Active secundary). */
  activeStyle?: 'primary' | 'secondary'
  /** Icono de la librería aplicado a todos los tabs del primary. */
  icon?: AndIconName
  /** Lado donde va el icono: izquierdo, derecho o ambos. */
  iconPosition?: 'left' | 'right' | 'both'
}

const props = withDefaults(defineProps<TabsProps>(), {
  variant: 'primary',
  activeStyle: 'primary',
  icon: undefined,
  iconPosition: 'both',
})

const model = defineModel<number>({ default: 0 })

const emit = defineEmits<{
  change: [index: number, item: TabItem]
}>()

const tabs = computed<TabItem[]>(() =>
  props.items.map((i) => (typeof i === 'string' ? { label: i } : i)),
)

const select = (index: number) => {
  if (tabs.value[index].disabled) return
  model.value = index
  emit('change', index, tabs.value[index])
}

// `icon` + `iconPosition` aplican a todos los tabs; el item puede
// sobreescribir con sus propios iconLeft/iconRight
const leftIconOf = (tab: TabItem) =>
  tab.iconLeft ??
  (props.icon && (props.iconPosition === 'left' || props.iconPosition === 'both')
    ? props.icon
    : undefined)

const rightIconOf = (tab: TabItem) =>
  tab.iconRight ??
  (props.icon && (props.iconPosition === 'right' || props.iconPosition === 'both')
    ? props.icon
    : undefined)
</script>

<template>
  <div
    v-if="variant === 'secondary'"
    class="and-tabs--segmented"
    role="tablist"
  >
    <button
      v-for="(tab, i) in tabs"
      :key="i"
      type="button"
      role="tab"
      :aria-selected="i === model"
      :class="['and-tabs__segment', i === model && 'and-tabs__segment--active']"
      @click="select(i)"
    >
      {{ tab.label }}
    </button>
  </div>
  <div
    v-else
    :class="['and-tabs', activeStyle === 'secondary' && 'and-tabs--secondary-style']"
    role="tablist"
  >
    <button
      v-for="(tab, i) in tabs"
      :key="i"
      type="button"
      role="tab"
      :aria-selected="i === model"
      :disabled="tab.disabled"
      :class="['and-tabs__tab', i === model && !tab.disabled && 'and-tabs__tab--active']"
      @click="select(i)"
    >
      <span class="and-tabs__tab-inner">
        <Icon v-if="leftIconOf(tab)" :name="leftIconOf(tab)!" :size="24" />
        {{ tab.label }}
        <Icon v-if="rightIconOf(tab)" :name="rightIconOf(tab)!" :size="24" />
      </span>
      <span class="and-tabs__bar" aria-hidden="true" />
    </button>
  </div>
</template>
