// vue/src/components/Tooltip/Tooltip.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import './Tooltip.css'

/*
 * Tooltip — DS Andromeda (Figma: set "Tooltips" 731:121, página
 * Tooltips 9454:21135). Globo de 12px (radius 4, padding 8/4, máx.
 * 254px) con flecha de 10x5 y sombra autolayout-sm; temas Light
 * (blanco/body) y Dark (secondary-dark/blanco). Envuelve cualquier
 * componente de la librería (slot) y aparece estrictamente en la
 * `position` indicada (top/bottom/left/right, centrado) al hacer
 * hover/focus, o controlado con `open`. La Direction de Figma nombra
 * el lado de la flecha (opuesto a la posición).
 */

export type TooltipPosition = 'top' | 'bottom' | 'left' | 'right'
export type TooltipTheme = 'light' | 'dark'

interface TooltipProps {
  /** Texto del globo (Figma: "Ejemplo"). */
  content: string
  /** Lado donde aparece el tooltip respecto al elemento envuelto. */
  position?: TooltipPosition
  /** Tema (Figma: Theme=Light|Dark). */
  theme?: TooltipTheme
  /** Visibilidad controlada; sin definir se muestra con hover/focus. */
  open?: boolean
}

const props = withDefaults(defineProps<TooltipProps>(), {
  position: 'top',
  theme: 'light',
  open: undefined,
})

const hovered = ref(false)
const visible = computed(() => (props.open !== undefined ? props.open : hovered.value))
</script>

<template>
  <span
    class="and-tooltip-wrap"
    @mouseenter="hovered = true"
    @mouseleave="hovered = false"
    @focusin="hovered = true"
    @focusout="hovered = false"
  >
    <slot />
    <span
      v-if="visible"
      :class="[
        'and-tooltip',
        `and-tooltip--${position}`,
        theme === 'dark' && 'and-tooltip--dark',
      ]"
      role="tooltip"
    >
      <span class="and-tooltip__bubble">{{ content }}</span>
      <span class="and-tooltip__arrow" aria-hidden="true" />
    </span>
  </span>
</template>

// react/src/components/Tooltip/Tooltip.tsx
import { useState, type HTMLAttributes, type ReactNode } from 'react'
import './Tooltip.css'

export type TooltipPosition = 'top' | 'bottom' | 'left' | 'right'
export type TooltipTheme = 'light' | 'dark'

export interface TooltipProps
  extends Omit<HTMLAttributes<HTMLSpanElement>, 'content'> {
  /** Texto del globo (Figma: "Ejemplo") */
  content: ReactNode
  /** Lado donde aparece el tooltip respecto al elemento envuelto */
  position?: TooltipPosition
  /** Tema (Figma: Theme=Light|Dark) */
  theme?: TooltipTheme
  /** Visibilidad controlada; sin definir se muestra con hover/focus */
  open?: boolean
  /** Elemento objetivo (cualquier componente de la librería) */
  children: ReactNode
}

export function Tooltip({
  content,
  position = 'top',
  theme = 'light',
  open,
  children,
  className = '',
  ...rest
}: TooltipProps) {
  const [hovered, setHovered] = useState(false)
  const visible = open !== undefined ? open : hovered

  return (
    <span
      className={['and-tooltip-wrap', className].filter(Boolean).join(' ')}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      onFocus={() => setHovered(true)}
      onBlur={() => setHovered(false)}
      {...rest}
    >
      {children}
      {visible && (
        <span
          className={[
            'and-tooltip',
            `and-tooltip--${position}`,
            theme === 'dark' && 'and-tooltip--dark',
          ]
            .filter(Boolean)
            .join(' ')}
          role="tooltip"
        >
          <span className="and-tooltip__bubble">{content}</span>
          <span className="and-tooltip__arrow" aria-hidden="true" />
        </span>
      )}
    </span>
  )
}
