// react/src/components/Modal/LabelBadge.tsx
import type { HTMLAttributes } from 'react'
import './Modal.css'

export type LabelBadgeEstado = 'success' | 'warning' | 'info' | 'danger'

export interface LabelBadgeProps extends HTMLAttributes<HTMLSpanElement> {
  /** Estado del badge (Figma: Label Success/Warning/Info/Danger) */
  estado?: LabelBadgeEstado
  /** Texto del badge (Figma: "Texto Badge") */
  text?: string
}

export function LabelBadge({
  estado = 'success',
  text = 'EJEMPLO',
  className = '',
  ...rest
}: LabelBadgeProps) {
  return (
    <span
      className={[
        'and-label-badge',
        estado !== 'success' && `and-label-badge--${estado}`,
        className,
      ]
        .filter(Boolean)
        .join(' ')}
      {...rest}
    >
      {text}
    </span>
  )
}

// vue/src/components/Modal/LabelBadge.vue
<script setup lang="ts">
import './Modal.css'

/*
 * LabelBadge — DS Andromeda (Figma: set "Label Badge" 191:2664).
 * Pastilla de 12px SemiBold (px 8 / py 4) con los 4 estados:
 * success/info/danger con texto blanco y warning con texto body.
 */

export type LabelBadgeEstado = 'success' | 'warning' | 'info' | 'danger'

interface LabelBadgeProps {
  /** Estado del badge (Figma: Label Success/Warning/Info/Danger). */
  estado?: LabelBadgeEstado
  /** Texto del badge (Figma: "Texto Badge"). */
  text?: string
}

withDefaults(defineProps<LabelBadgeProps>(), {
  estado: 'success',
  text: 'EJEMPLO',
})
</script>

<template>
  <span :class="['and-label-badge', estado !== 'success' && `and-label-badge--${estado}`]">
    {{ text }}
  </span>
</template>
